blank_issues_enabled: true
contact_links:
    - name: Questions and ideas
      url: https://github.com/hojttaler/Resolvr/discussions
      about: Ask how to do something or discuss an idea before opening an issue.
